create table drinks
(
    id          int generated by default as identity primary key,
    name        varchar not null unique,
    is_standard boolean not null default false
);

create table ingredients
(
    id       int generated by default as identity primary key,
    name     varchar not null unique,
    quantity int default 0,
    unit     varchar not null
);

create table drinks_ingredients
(
    id            int generated by default as identity primary key,
    drink_id      int references drinks (id),
    ingredient_id int references ingredients (id),
    quantity int not null
);

create table statistics
(
    id         int generated by default as identity primary key,
    drink_id   int references drinks (id),
    order_date date
);